### ISSUE TITLE
access status 

### ISSUE THREAD

**Issue by roxannewyns** [libis/pa_mjb#1]
objects with the status 'non accessible au public' should not be published on pawtcuket. Only 'accessible au public' should be published. This is currently not the case.

E.g.
pa_mjb/index.php/Detail/objects/6699
ca_mjb_test/index.php/editor/objects/ObjectEditor/Edit/Screen44/object_id/6699

![image](https://user-images.githubusercontent.com/3798589/31538095-c27ce312-b004-11e7-97b7-68c93389c152.png)

![image](https://user-images.githubusercontent.com/3798589/31538149-ee71bcc2-b004-11e7-8898-4c29751dd752.png)

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/heron_configuratie/commit/7d754959e8890104929312c4eff3b25dc0f9d87c and https://github.com/libis/pa_mjb/commit/65498c629c7aabb47a3419b3c11ead6082900544
